version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    # 配置版本策略
    versioning-strategy: increase
    # 忽略传递依赖项更新，避免 pnpm 不支持的功能
    ignore:
      - dependency-name: "brace-expansion"
        dependency-type: "indirect"
      # 忽略其他可能导致问题的传递依赖
      - dependency-name: "*"
        dependency-type: "indirect"
        update-types: ["version-update:semver-patch"]
    # 限制 PR 数量
    open-pull-requests-limit: 3
    # 配置提交消息
    commit-message:
      prefix: "deps"
      include: "scope"
    # 配置标签
    labels:
      - "dependencies"
      - "automated"
    # 只更新直接依赖，避免传递依赖问题
    allow:
      - dependency-type: "direct"